version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  jobs:
    pre_install:
      - python -m pip install --no-cache-dir pybind11[global]

# Build PDF
formats:
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: python
  system_packages: true
